// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric/core/ledger"
)

type QueryExecutorProvider struct {
	NewQueryExecutorStub        func() (ledger.QueryExecutor, error)
	newQueryExecutorMutex       sync.RWMutex
	newQueryExecutorArgsForCall []struct{}
	newQueryExecutorReturns     struct {
		result1 ledger.QueryExecutor
		result2 error
	}
	newQueryExecutorReturnsOnCall map[int]struct {
		result1 ledger.QueryExecutor
		result2 error
	}
	NewQueryExecutorNoLockStub        func() (ledger.QueryExecutor, error)
	newQueryExecutorNoLockMutex       sync.RWMutex
	newQueryExecutorNoLockArgsForCall []struct{}
	newQueryExecutorNoLockReturns     struct {
		result1 ledger.QueryExecutor
		result2 error
	}
	newQueryExecutorNoLockReturnsOnCall map[int]struct {
		result1 ledger.QueryExecutor
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *QueryExecutorProvider) NewQueryExecutor() (ledger.QueryExecutor, error) {
	fake.newQueryExecutorMutex.Lock()
	ret, specificReturn := fake.newQueryExecutorReturnsOnCall[len(fake.newQueryExecutorArgsForCall)]
	fake.newQueryExecutorArgsForCall = append(fake.newQueryExecutorArgsForCall, struct{}{})
	fake.recordInvocation("NewQueryExecutor", []interface{}{})
	fake.newQueryExecutorMutex.Unlock()
	if fake.NewQueryExecutorStub != nil {
		return fake.NewQueryExecutorStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.newQueryExecutorReturns.result1, fake.newQueryExecutorReturns.result2
}

func (fake *QueryExecutorProvider) NewQueryExecutorCallCount() int {
	fake.newQueryExecutorMutex.RLock()
	defer fake.newQueryExecutorMutex.RUnlock()
	return len(fake.newQueryExecutorArgsForCall)
}

func (fake *QueryExecutorProvider) NewQueryExecutorReturns(result1 ledger.QueryExecutor, result2 error) {
	fake.NewQueryExecutorStub = nil
	fake.newQueryExecutorReturns = struct {
		result1 ledger.QueryExecutor
		result2 error
	}{result1, result2}
}

func (fake *QueryExecutorProvider) NewQueryExecutorReturnsOnCall(i int, result1 ledger.QueryExecutor, result2 error) {
	fake.NewQueryExecutorStub = nil
	if fake.newQueryExecutorReturnsOnCall == nil {
		fake.newQueryExecutorReturnsOnCall = make(map[int]struct {
			result1 ledger.QueryExecutor
			result2 error
		})
	}
	fake.newQueryExecutorReturnsOnCall[i] = struct {
		result1 ledger.QueryExecutor
		result2 error
	}{result1, result2}
}

func (fake *QueryExecutorProvider) NewQueryExecutorNoLock() (ledger.QueryExecutor, error) {
	fake.newQueryExecutorNoLockMutex.Lock()
	ret, specificReturn := fake.newQueryExecutorNoLockReturnsOnCall[len(fake.newQueryExecutorNoLockArgsForCall)]
	fake.newQueryExecutorNoLockArgsForCall = append(fake.newQueryExecutorNoLockArgsForCall, struct{}{})
	fake.recordInvocation("NewQueryExecutorNoLock", []interface{}{})
	fake.newQueryExecutorNoLockMutex.Unlock()
	if fake.NewQueryExecutorNoLockStub != nil {
		return fake.NewQueryExecutorNoLockStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.newQueryExecutorNoLockReturns.result1, fake.newQueryExecutorNoLockReturns.result2
}

func (fake *QueryExecutorProvider) NewQueryExecutorNoLockCallCount() int {
	fake.newQueryExecutorNoLockMutex.RLock()
	defer fake.newQueryExecutorNoLockMutex.RUnlock()
	return len(fake.newQueryExecutorNoLockArgsForCall)
}

func (fake *QueryExecutorProvider) NewQueryExecutorNoLockReturns(result1 ledger.QueryExecutor, result2 error) {
	fake.NewQueryExecutorNoLockStub = nil
	fake.newQueryExecutorNoLockReturns = struct {
		result1 ledger.QueryExecutor
		result2 error
	}{result1, result2}
}

func (fake *QueryExecutorProvider) NewQueryExecutorNoLockReturnsOnCall(i int, result1 ledger.QueryExecutor, result2 error) {
	fake.NewQueryExecutorNoLockStub = nil
	if fake.newQueryExecutorNoLockReturnsOnCall == nil {
		fake.newQueryExecutorNoLockReturnsOnCall = make(map[int]struct {
			result1 ledger.QueryExecutor
			result2 error
		})
	}
	fake.newQueryExecutorNoLockReturnsOnCall[i] = struct {
		result1 ledger.QueryExecutor
		result2 error
	}{result1, result2}
}

func (fake *QueryExecutorProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newQueryExecutorMutex.RLock()
	defer fake.newQueryExecutorMutex.RUnlock()
	fake.newQueryExecutorNoLockMutex.RLock()
	defer fake.newQueryExecutorNoLockMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *QueryExecutorProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
