// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric/msp"
)

type IdentityDeserializerProvider struct {
	GetIdentityDeserializerStub        func(channelID string) msp.IdentityDeserializer
	getIdentityDeserializerMutex       sync.RWMutex
	getIdentityDeserializerArgsForCall []struct {
		channelID string
	}
	getIdentityDeserializerReturns struct {
		result1 msp.IdentityDeserializer
	}
	getIdentityDeserializerReturnsOnCall map[int]struct {
		result1 msp.IdentityDeserializer
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IdentityDeserializerProvider) GetIdentityDeserializer(channelID string) msp.IdentityDeserializer {
	fake.getIdentityDeserializerMutex.Lock()
	ret, specificReturn := fake.getIdentityDeserializerReturnsOnCall[len(fake.getIdentityDeserializerArgsForCall)]
	fake.getIdentityDeserializerArgsForCall = append(fake.getIdentityDeserializerArgsForCall, struct {
		channelID string
	}{channelID})
	fake.recordInvocation("GetIdentityDeserializer", []interface{}{channelID})
	fake.getIdentityDeserializerMutex.Unlock()
	if fake.GetIdentityDeserializerStub != nil {
		return fake.GetIdentityDeserializerStub(channelID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getIdentityDeserializerReturns.result1
}

func (fake *IdentityDeserializerProvider) GetIdentityDeserializerCallCount() int {
	fake.getIdentityDeserializerMutex.RLock()
	defer fake.getIdentityDeserializerMutex.RUnlock()
	return len(fake.getIdentityDeserializerArgsForCall)
}

func (fake *IdentityDeserializerProvider) GetIdentityDeserializerArgsForCall(i int) string {
	fake.getIdentityDeserializerMutex.RLock()
	defer fake.getIdentityDeserializerMutex.RUnlock()
	return fake.getIdentityDeserializerArgsForCall[i].channelID
}

func (fake *IdentityDeserializerProvider) GetIdentityDeserializerReturns(result1 msp.IdentityDeserializer) {
	fake.GetIdentityDeserializerStub = nil
	fake.getIdentityDeserializerReturns = struct {
		result1 msp.IdentityDeserializer
	}{result1}
}

func (fake *IdentityDeserializerProvider) GetIdentityDeserializerReturnsOnCall(i int, result1 msp.IdentityDeserializer) {
	fake.GetIdentityDeserializerStub = nil
	if fake.getIdentityDeserializerReturnsOnCall == nil {
		fake.getIdentityDeserializerReturnsOnCall = make(map[int]struct {
			result1 msp.IdentityDeserializer
		})
	}
	fake.getIdentityDeserializerReturnsOnCall[i] = struct {
		result1 msp.IdentityDeserializer
	}{result1}
}

func (fake *IdentityDeserializerProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getIdentityDeserializerMutex.RLock()
	defer fake.getIdentityDeserializerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IdentityDeserializerProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
